# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Bootstrap row means
#'
#' This takes a numeric matrix, bootstrap resamples each row, and then
#' calculates the mean. The intended use case is for Bayesian posterior
#' predictions from sample data. Instead of directly calculating the
#' average marginal effect (AME) across all observed values, these can be
#' bootstrapped, so that uncertainty in the target population, and thus
#' the AME in the target population, can be incorporated.
#' Model uncertainty is already assumed to be handled by the different posterior
#' samples, which are assumed to be across rows.
#' 
#' @param x A numeric matrix 
#' @return A numeric vector with the simple bootstrapped row means of the matrix
#' @export
#' @examples
#'
#' x <- matrix(1:9, byrow = TRUE, 3)
#' replicate(10, rowBootMeans(x))
rowBootMeans <- function(x) {
    .Call('_brmsmargins_rowBootMeans', PACKAGE = 'brmsmargins', x)
}

